/**
 *
 * @author Janel Garces Castillo
 * @version 1.0
 * @since 1.0
 *
 *
 */
package cr.ac.una.reg.info.sql;


public class PersonaSQL {

    public synchronized static String listarPersona() {
        String sql = "SELECT IDENTIFICACION, CODIGO_TIPO_IDENTIFICACION, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, CONOCIDO_COMO, FECHA_NACIMIENTO, CODIGO_COLEGIO, ANIO_GRADUACION_COLEGIO, NOTA_COLEGIO, INDIGENA, CODIGO_TERRITORIO, CODIGO_GRUPO_INDIGENA, TELEFONO, TELEFONO2, CORREO_ELECTRONICO, ESTADO_EN_SISTEMA FROM DR_SGII_PERSONA";
        return sql;
    }
    

    
    public synchronized static String modificarPersonaConsulta() {
        String sql = "update DR_SGII_PERSONA set NOMBRE =?, PRIMER_APELLIDO =?, SEGUNDO_APELLIDO =?, CONOCIDO_COMO =?, CODIGO_COLEGIO=?, ANIO_GRADUACION_COLEGIO =?, NOTA_COLEGIO=?, CODIGO_TERRITORIO=?, CODIGO_GRUPO_INDIGENA=?, CORREO_ELECTRONICO=?, TELEFONO =?, TELEFONO2=?, ESTADO_EN_SISTEMA=? WHERE IDENTIFICACION =?";
        return sql;
    }
    
    public synchronized static String detallePersona() {
        String sql = "SELECT IDENTIFICACION, CODIGO_TIPO_IDENTIFICACION, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, CONOCIDO_COMO, FECHA_NACIMIENTO, CODIGO_COLEGIO, ANIO_GRADUACION_COLEGIO, NOTA_COLEGIO, INDIGENA, CODIGO_TERRITORIO, TELEFONO,TELEFONO2, CORREO_ELECTRONICO, CODIGO_GRUPO_INDIGENA, ESTADO_EN_SISTEMA FROM DR_SGII_PERSONA WHERE IDENTIFICACION=? ";
        return sql;
    }
    
    /** Sheng Yuan Lin **/
    public synchronized static String ingresarPersona(){
    String sql="INSERT INTO DR_SGII_PERSONA(IDENTIFICACION,CODIGO_TIPO_IDENTIFICACION,NOMBRE,PRIMER_APELLIDO,"
            + "SEGUNDO_APELLIDO,FECHA_NACIMIENTO,CODIGO_COLEGIO,ANIO_GRADUACION_COLEGIO,"
            + "NOTA_COLEGIO,INDIGENA,CODIGO_TERRITORIO,CODIGO_GRUPO_INDIGENA,TELEFONO,CORREO_ELECTRONICO,ESTADO_EN_SISTEMA) VALUES "
            + "(?,?,?,?,?,TO_DATE(?,'DD/MM/YYYY'),?,?,?,?,?,?,?,?,?)";
    return sql;
    }
}
