REM INSERTING into REG_GENERAL_ESTADO_CIVIL
SET DEFINE OFF;
Insert into REG_GENERAL_ESTADO_CIVIL (CODIGO,DESCRIPCION) values ('P','SEPARADO(A)');
Insert into REG_GENERAL_ESTADO_CIVIL (CODIGO,DESCRIPCION) values ('U','UNION LIBRE');
Insert into REG_GENERAL_ESTADO_CIVIL (CODIGO,DESCRIPCION) values ('V','VIUDO(A)');
Insert into REG_GENERAL_ESTADO_CIVIL (CODIGO,DESCRIPCION) values ('S','SOLTERO(A)');
Insert into REG_GENERAL_ESTADO_CIVIL (CODIGO,DESCRIPCION) values ('M','CASADO(A)');
Insert into REG_GENERAL_ESTADO_CIVIL (CODIGO,DESCRIPCION) values ('D','DIVORCIADO(A)');

--****************************************************************
EXIT
