REM INSERTING into REG_GENERAL_CARRERA
SET DEFINE OFF;
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('159','Lengua Francesa - Campus Omar Dengo (Heredia)','BA-LENFRA','6');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('161','Comercio y Negocios Internacionales - Campus Omar Dengo (Heredia)','BA-CONEIN','408');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('162','Teología (Virtual) - Campus Omar Dengo (Heredia)','BA-TEOLOG','18');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('163','Literatura y Lingüística con Énfasis en Español - Campus Omar Dengo (Heredia)','BA-LITERA','354');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('165','Enseñanza de la Religión (Virtual) - Campus Omar Dengo (Heredia)','BA-RELIGI','20');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('166','Diplomado en Acuicultura - (ECMAR - Puntarenas)','DI-ACUICUL','436');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('201','Administración - Campus Liberia','BA-ADMINI','50');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('202','Gestión Empresarial del Turismo Sostenible - Campus Liberia','BA-TURISM','202');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('205','Inglés (Diplomado) - Campus Liberia','DI-INGLES','380');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('209','Ingeniería en Sistemas de Información - Campus Liberia','BA-INFORM','372');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('301','Administración - Campus Nicoya','BA-ADMINI','51');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('302','Gestión Empresarial del Turismo Sostenible - Campus Nicoya','BA-TURISM','203');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('305','Inglés (Diplomado) - Campus Nicoya','DI-INGLES','381');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('306','Ingeniería en Sistemas de Información - Campus Nicoya','BA-INFORM','374');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('308','Comercio y Negocios Internacionales - Campus Nicoya','BA-CONEIN','424');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('407','Gestión Empresarial del Turismo Sostenible  - Campus Pérez Zeledón','BA-TURISM','204');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('408','Administración  - Campus Pérez Zeledón','BA-ADMINI','52');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('409','Ingeniería en Sistemas de Información  - Campus Pérez Zeledón','BA-INFORM','95');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('501','Administración  - Campus Coto','BA-ADMINI','53');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('502','Gestión Empresarial del Turismo Sostenible - Campus Coto','BA-TURISM','0');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('505','Ingeniería en Sistemas de Información  - Campus Coto','BA-INFORM','96');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('509','Enseñanza del Inglés - Campus Coto','BA-INGLES','435');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('601','Ingeniería en Sistemas de Información (Acreditada) - Interuniversitaria de Alajuela','BA-INFORM','504');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('701','Administración - Región Huetar Norte-Caribe (Sarapiquí)','BA-ADMINI','399');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('702','Programación de Aplicaciones Informáticas (Diplomado) - Sarapiquí','DI-INFORM','0');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('704','Secretariado Profesional - Sarapiquí','DI-SECPRO','0');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('705','Recreación Turística (Diplomado) - Región Huetar Norte-Caribe (Sarapiquí)','DI-RETURIST','0');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('706','Gestión Integral de Fincas (Diplomado) - Región Huetar Norte-Caribe (Sarapiquí)','DI-GEINFI','427');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('606','Inglés (Bachillerato) (Salida lateral al Diplomado) - Interuniversitaria de Alajuela','BA-INGLDP','453');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('179','Entomología Médica - Campus Benjamín Núñez (Barreal de Heredia)','DI-ENTMED','484');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('512','Administración de Oficinas - Campus Coto','BA-ADMOFI','496');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('419','Enseñanza de la Educación Física, Deporte y Recreación - Campus Pérez Zeledón','BA-ENEDFI','500');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('711','Educación con Énfasis en Educación Rural I y II Ciclos - Región Huetar Norte-Caribe (Sarapiquí)','DI-ERURAL','407');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('214','Recurso Hídrico - Liberia *',null,'0');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('211','Comercio y Negocios Internacionales - Campus Liberia','BA-CONEIN','423');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('178','Género y Desarrollo - Campus Omar Dengo (Heredia)','BA-GENERO','31');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('174','Ingeniería en Gestión Ambiental - Campus Omar Dengo (Heredia)','BA-INGESA','450');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('000','Música con Énfasis en la Ejecución y Enseñanza Instrumento - Sede Central','LI-MUEINS',null);
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('708','Administración de Oficinas (Salida lat. Dipl. Secret. Prof) - Región Huetar Norte-Caribe (Sarapiquí)','BA-ADMOFI','471');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('176','Inglés (Bachillerato) (Salida lateral al Diplomado) - Campus Omar Dengo (Heredia)','BA-INGLDP','452');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('511','Comercio y Negocios Internacionales* - Campus Coto','BA-CONEIN','473');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('416','Administración de Oficinas - Campus Pérez Zeledón','BA-ADMOFI','485');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('417','Comercio y Negocios Internacionales* - Campus Pérez Zeledón','BA-CONEIN','461');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('418','Trabajo Social* - Pérez Zeledón',null,'0');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('710','Gestión en Recreación y Turismo - Región Huetar Norte-Caribe (Sarapiquí)','BA-GERETU','481');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('304','Enseñanza del Inglés - Nicoya','BA-INGLES','12');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('303','Pedagogía con Énfasis en I y II Ciclos de la Educación General Básica - Campus Nicoya','BA-PEDAGP','154');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('204','Enseñanza del Inglés - Liberia','BA-INGLES','11');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('203','Pedagogía con Énfasis en I y II Ciclos de la Educación General Básica - Campus Liberia','BA-EDESPE','377');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('164','Ingeniería en Bioprocesos Industriales - Campus Omar Dengo (Heredia)','BA-BIOPRIN','454');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('160','Bibliotecología Pedagógica - Campus Omar Dengo (Heredia)','DI-BIPEDAG','0');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('154','Música con Énfasis en la Interpretación y Enseñanza del Canto - Campus Omar Dengo (Heredia)','BA-MUECAN','190');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('309','Arte y Comunicación Visual con Énfasis en Diseño Gráfico - Nicoya','BA-ARTCOV','0');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('128','Ingeniería en Agronomía (Acreditada) - Campus Omar Dengo (Heredia)','BA-AGRONO','109');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('130','Ingeniería en Ciencias  Forestales (Acreditada) - Campus Omar Dengo (Heredia)','BA-FOREST','119');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('137','Orientación (Acreditada) - Campus Omar Dengo (Heredia)','BA-ORIENT','165');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('401','Enseñanza del Inglés  - Campus Pérez Zeledón','BA-INGLES','13');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('410','Inglés (Diplomado) - Campus Pérez Zeledón','DI-INGLES','382');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('414','Enseñanza de las Ciencias* - Pérez Zeledón','PR-ENSCIE','0');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('602','Química Industrial - Interuniversitaria de Alajuela','BA-QUIMIC','505');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('604','Inglés (Diplomado) - Interuniversitaria de Alajuela','DI-INGLES','0');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('605','Administración - Interuniversitaria de Alajuela','BA-ADMINI','444');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('707','Ingeniería en Sistemas de Información* - Región Huetar Norte-Caribe (Sarapiquí)','BA-INFORM','469');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('709','Gestión en Recreación Turística* - Región Huetar Norte-Caribe (Sarapiquí)','DI-RETURIS','468');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('100','En Blanco',null,null);
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('415','Gestión Integral de Fincas* - Pérez Zeledón','DI-GEINFI','0');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('126','Informática Educativa - Sede Central','BA-INFOED','0');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('138','Educación con Énfasis en Educación Rural I y II Ciclos - Sede Central','DI-ERURAL','173');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('107','Enseñanza de la Filosofía - Campus Omar Dengo (Heredia)','BA-ENFILO','26');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('310','Gestión Integral de Fincas - Nicoya *','DI-GEINFI','0');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('215','Ingeniería Hidrológica - Campus Liberia','BA-INGHID','482');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('213','Gestión Integral de Fincas - Liberia *','DI-GEINFI','0');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('170','Licenciatura en Género',null,'0');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('149','Música con Énfasis en la Ejecución y Enseñanza del Instrumento: Percusión- Campus Omar Dengo (Heredi','BA-MUEINS','194');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('139','Arte Escénico - Campus Omar Dengo (Heredia)','BA-ARTESC','178');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('151','Música con Énfasis en la Ejecución y Enseñanza del Instrumento: Saxofón- Campus Omar Dengo (Heredia)','BA-MUEINS','194');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('212','Arte y Comunicación Visual con Énfasis en Diseño Gráfico - Liberia','BA-ARTCOV','0');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('148','Música con Énfasis en la Ejecución y Enseñanza del Instrumento: Piano - Campus Omar Dengo (Heredia)','BA-MUEINS','194');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('147','Música con Énfasis en la Ejecución y Enseñanza del Instrumento: Guitarra -Campus Omar Dengo (Hdia)','BA-MUEINS','194');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('146','Música con Énfasis en la Ejecución y Enseñanza del Instrumento: Flauta Traversa -Campus Omar Dengo ','BA-MUEINS','194');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('145','Música con Énfasis en la Ejecución y Enseñanza del Instrumento: Clarinete -Campus Omar Dengo (Hdia)','BA-MUEINS','194');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('144','Música con Énfasis en la Interpretación y Enseñanza de la Dirección Coral - Campus Omar Dengo (Hdia)','BA-MUDICO','192');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('143','Música con Énfasis en Educación  Musical - Campus Omar Dengo (Heredia)','BA-MUEDMU','187');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('142','Danza (Acreditada) - Campus Omar Dengo (Heredia)','BA-DANZA','185');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('141','Enseñanza del Arte y Comunicación Visual - Campus Omar Dengo (Heredia)','BA-ENACOV','183');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('140','Arte y Comunicación Visual - Campus Omar Dengo (Heredia)','BA-ARTCOV','180');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('150','Música con Énfasis en la Ejecución y Enseñanza del Instrumento: Trompeta- Campus Omar Dengo (Heredia','BA-MUEINS','194');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('101','Enseñanza del Español - Campus Omar Dengo (Heredia)','BA-ESPAÑO','1');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('102','Enseñanza del Francés (Acreditada) - Campus Omar Dengo (Heredia)','BA-ENFRAN','7');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('103','Enseñanza del Inglés (Acreditada) - Campus Omar Dengo (Heredia)','BA-INGLES','10');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('105','Bibliotecología y Documentación - Campus Omar Dengo (Heredia)','BA-BIGEIN','517');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('106','Filosofía - Campus Omar Dengo (Heredia)','BA-FILOSO','25');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('108','Gestión de Desarrollo Sostenible con Equidad de Género - Campus Omar Dengo (Heredia)','BA-GENERO','31');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('110','Historia - Campus Omar Dengo (Heredia)','BA-HISTOR','38');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('111','Enseñanza de los Estudios Sociales y Educación Cívica (Acreditada) - Campus Omar Dengo (Heredia)','BA-ESTSOC','36');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('112','Sociología - Campus Omar Dengo (Heredia)','BA-SOCIOL','41');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('113','Planificación Económica y Promoción Social (Acreditada) - Campus Omar Dengo (Heredia)','BA-PLANIF','47');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('114','Administración (Acreditada) - Campus Omar Dengo (Heredia)','BA-ADMINI','49');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('115','Educación Comercial (Salida lateral al Diplomado) (Acreditada) - Campus Omar Dengo (Heredia)','BA-EDUCOM','61');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('116','Administración de Oficinas (Salida lateral Dipl. Secret. Profesional) - Campus Omar Dengo (Heredia)','BA-ADMOFI','64');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('117','Relaciones Internacionales (Acreditada) - Campus Omar Dengo (Heredia)','BA-RELINT','66');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('118','Economía (Acreditada) - Campus Omar Dengo (Heredia)','BA-ECONOMI','519');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('119','Psicología - Campus Omar Dengo (Heredia)','BA-PSICOL','72');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('120','Enseñanza de la Matemática (Acreditada) - Campus Omar Dengo (Heredia)','BA-MATEMA','78');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('121','Enseñanza de las Ciencias (Acreditada) - Campus Omar Dengo (Heredia)','BA-ENSCIE','81');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('122','Biología (Acreditada) - Campus Omar Dengo (Heredia)','BA-BIOLOG','83');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('123','Química Industrial  - Campus Omar Dengo (Heredia)','BA-QUIMIC','86');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('124','Ingeniería en Topografía y Catastro (Acreditada) - Campus Omar Dengo (Heredia)','BA-TOPOGR','89');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('125','Ingeniería en Sistemas de Información (Acreditada) -  Campus Benjamín Núñez (Barreal de Heredia)','BA-INFORM','466');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('127','Ciencias Geográficas (Acreditada) - Campus Omar Dengo (Heredia)','BA-GEOGRA','106');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('129','Gestión Ambiental  - Sede Central','LI-GESAMB','0');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('131','Cartografía y Diseño Digital (Diplomado) - Campus Omar Dengo (Heredia)','DI-CARTOG','105');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('132','Medicina Veterinaria (Acreditada) -  Campus Benjamín Núñez (Barreal de Heredia)','LI-VETERI','126');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('133','Ens. de la Educ. Física, Deporte y Recreación (Acreditada) - Campus Benjamín Núñez (Barreal de Hdia)','BA-ENEDFI','133');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('134','Pedagogía con Énfasis en Educación Preescolar - Campus Omar Dengo (Heredia)','DI-PRESCO','138');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('135','Pedag. con Énfa. en I y II Ciclos de la Educ. General Básica (Acreditada) - Campus Omar Dengo (Hdia)','BA-PEDAGP','152');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('136','Educación Especial (Acreditada) - Campus Omar Dengo (Heredia)','BA-EDESPE','162');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('155','Enseñanza del Inglés para I y II Ciclos (Acreditada) - Campus Omar Dengo (Heredia)','BA-ENSING','197');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('157','Promoción de la Salud Física (Acreditada) -  Campus Benjamín Núñez (Barreal de Heredia)','BA-PRSAFI','136');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('158','Inglés (Diplomado) - Sede Central','DI-INGLES','379');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('180','Música con Énfasis en la Ejecución y Enseñanza del Instrumento: Violín','BA-MUEINS','194');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('181','Música con Énfasis en la Ejecución y Enseñanza del Instrumento: Viola','BA-MUEINS','194');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('182','Música con Énfasis en la Ejecución y Enseñanza del Instrumento: Violoncello.','BA-MUEINS','194');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('413','Planificación Económica y Social - Campus Pérez Zeledón','NO-DECLAR','0');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('183','Bibliotecología y Gestión de la Información (Acreditada) - Campus Omar Dengo (Heredia)','BA-BIGEIN','517');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('184','Ingeniería y Calidad en Innovación Agroalimentaria','BA-ICIAGRO','522');
Insert into REG_GENERAL_CARRERA (CODIGO,DESCRIPCION,CODIGO_BANNER,REGLA) values ('185','Pedagogía con Énfasis en Educación Preescolar y Primera Infancia (Acreditada)-Campus Omar Dengo','BA-PRESCO','141');

exit