drop table STVCOLL;
drop table SMRPRLE;
drop table STVNATN;
drop table STVTERM;
drop table REG_ADMIS_TIPO_IDENTIFICACION;
drop table GTVZIPC;
drop table REG_GENERAL_COLEGIO;
drop table REG_GENERAL_ESTADO_CIVIL;
drop table STVATTS;



--*************ESCUELA*****************************

CREATE TABLE "REGISTRO"."STVCOLL" 
   (
    "STVCOLL_CODE" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	"STVCOLL_DESC" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"STVCOLL_ADDR_STREET_LINE1" VARCHAR2(75 CHAR), 
	"STVCOLL_ADDR_STREET_LINE2" VARCHAR2(75 CHAR), 
	"STVCOLL_ADDR_STREET_LINE3" VARCHAR2(75 CHAR), 
	"STVCOLL_ADDR_CITY" VARCHAR2(50 CHAR), 
	"STVCOLL_ADDR_STATE" VARCHAR2(2 CHAR), 
	"STVCOLL_ADDR_COUNTRY" VARCHAR2(28 CHAR), 
	"STVCOLL_ADDR_ZIP_CODE" VARCHAR2(10 CHAR), 
	"STVCOLL_ACTIVITY_DATE" DATE, 
	"STVCOLL_SYSTEM_REQ_IND" VARCHAR2(1 CHAR), 
	"STVCOLL_VR_MSG_NO" NUMBER(6,0), 
	"STVCOLL_STATSCAN_CDE3" VARCHAR2(6 CHAR), 
	"STVCOLL_DICD_CODE" VARCHAR2(3 CHAR), 
	"STVCOLL_HOUSE_NUMBER" VARCHAR2(10 CHAR), 
	"STVCOLL_ADDR_STREET_LINE4" VARCHAR2(75 CHAR), 
	"STVCOLL_SURROGATE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"STVCOLL_VERSION" NUMBER(19,0) NOT NULL ENABLE, 
	"STVCOLL_USER_ID" VARCHAR2(30 CHAR), 
	"STVCOLL_DATA_ORIGIN" VARCHAR2(30 CHAR), 
	"STVCOLL_VPDI_CODE" VARCHAR2(6 CHAR),
    CONSTRAINT "STVCOL_PK" PRIMARY KEY(STVCOLL_CODE)
    ); 

--************CARRERA*******************************

CREATE TABLE "REGISTRO"."REG_GENERAL_CARRERA" 
	(	
	"CODIGO" VARCHAR2(10 CHAR), 
	"DESCRIPCION" VARCHAR2(100 CHAR), 
	"CODIGO_BANNER" VARCHAR2(20 CHAR), 
	"REGLA" NUMBER, 
	 PRIMARY KEY ("CODIGO")
	);

--*****************PAIS***********************

CREATE TABLE "REGISTRO"."STVNATN" 
   (	
    "STVNATN_CODE" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"STVNATN_NATION" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"STVNATN_CAPITAL" VARCHAR2(20 CHAR), 
	"STVNATN_AREA" NUMBER(22,0), 
	"STVNATN_POPULATION" NUMBER(22,0), 
	"STVNATN_ACTIVITY_DATE" DATE NOT NULL ENABLE, 
	"STVNATN_EDI_EQUIV" VARCHAR2(2 CHAR), 
	"STVNATN_LMS_EQUIV" VARCHAR2(2 CHAR), 
	"STVNATN_POSTAL_MASK" VARCHAR2(15 CHAR), 
	"STVNATN_TELE_MASK" VARCHAR2(15 CHAR), 
	"STVNATN_STATSCAN_CDE" VARCHAR2(5 CHAR), 
	"STVNATN_SCOD_CODE_ISO" VARCHAR2(3 CHAR), 
	"STVNATN_SSA_REPORTING_EQUIV" VARCHAR2(2 CHAR), 
	"STVNATN_SEVIS_EQUIV" VARCHAR2(2 CHAR), 
	"STVNATN_SURROGATE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"STVNATN_VERSION" NUMBER(19,0) NOT NULL ENABLE, 
	"STVNATN_USER_ID" VARCHAR2(30 CHAR), 
	"STVNATN_DATA_ORIGIN" VARCHAR2(30 CHAR), 
	"STVNATN_VPDI_CODE" VARCHAR2(6 CHAR),
    CONSTRAINT "STVNATN_PK" PRIMARY KEY(STVNATN_CODE)
   );

--**************PERIODO*********************

CREATE TABLE "REGISTRO"."STVTERM" 
   (	
    "STVTERM_CODE" VARCHAR2(6 CHAR) NOT NULL ENABLE, 
	"STVTERM_DESC" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"STVTERM_START_DATE" DATE NOT NULL ENABLE, 
	"STVTERM_END_DATE" DATE NOT NULL ENABLE, 
	"STVTERM_FA_PROC_YR" VARCHAR2(4 CHAR), 
	"STVTERM_ACTIVITY_DATE" DATE NOT NULL ENABLE, 
	"STVTERM_FA_TERM" VARCHAR2(1 CHAR), 
	"STVTERM_FA_PERIOD" NUMBER(2,0), 
	"STVTERM_FA_END_PERIOD" NUMBER(2,0), 
	"STVTERM_ACYR_CODE" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
	"STVTERM_HOUSING_START_DATE" DATE NOT NULL ENABLE, 
	"STVTERM_HOUSING_END_DATE" DATE NOT NULL ENABLE, 
	"STVTERM_SYSTEM_REQ_IND" VARCHAR2(1 CHAR), 
	"STVTERM_TRMT_CODE" VARCHAR2(1 CHAR), 
	"STVTERM_FA_SUMMER_IND" VARCHAR2(1 CHAR), 
	"STVTERM_SURROGATE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"STVTERM_VERSION" NUMBER(19,0) NOT NULL ENABLE, 
	"STVTERM_USER_ID" VARCHAR2(30 CHAR), 
	"STVTERM_DATA_ORIGIN" VARCHAR2(30 CHAR), 
	"STVTERM_VPDI_CODE" VARCHAR2(6 CHAR),
    CONSTRAINT "STVTERM_PK" PRIMARY KEY(STVTERM_CODE)
   );

   --************TIPO_IDENTIFICACION********************

CREATE TABLE "REGISTRO"."REG_ADMIS_TIPO_IDENTIFICACION" 
   (	"CODIGO" VARCHAR2(10 CHAR), 
	"DESCRIPCION" VARCHAR2(100 CHAR),
	CONSTRAINT "TIPO_IDENTIFICACION_PK" PRIMARY KEY(CODIGO)
   );

--********DIRECCION******************

CREATE TABLE "REGISTRO"."GTVZIPC" 
   (	
    "GTVZIPC_CODE" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"GTVZIPC_CITY" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"GTVZIPC_STAT_CODE" VARCHAR2(3 CHAR), 
	"GTVZIPC_NATN_CODE" VARCHAR2(5 CHAR), 
	"GTVZIPC_ACTIVITY_DATE" DATE NOT NULL ENABLE, 
	"GTVZIPC_USER_ID" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"GTVZIPC_CNTY_CODE" VARCHAR2(5 CHAR), 
	"GTVZIPC_SURROGATE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"GTVZIPC_VERSION" NUMBER(19,0) NOT NULL ENABLE, 
	"GTVZIPC_DATA_ORIGIN" VARCHAR2(30 CHAR), 
	"GTVZIPC_VPDI_CODE" VARCHAR2(6 CHAR),
    CONSTRAINT GTVZIPC_PK PRIMARY KEY(GTVZIPC_CODE)
   );

--****************COLEGIO*******************

CREATE TABLE "REGISTRO"."REG_GENERAL_COLEGIO" 
   (	
    "CODIGO" VARCHAR2(10 CHAR), 
	"DESCRIPCION" VARCHAR2(100 CHAR), 
	"ESTRATO" NUMBER, 
	"CODIGO_BANNER" VARCHAR2(10 CHAR), 
	"COD_MODALIDAD" VARCHAR2(2 CHAR), 
	"COD_SITUACION" VARCHAR2(2 CHAR), 
	"COD_TIPO_BACHILLERATO" VARCHAR2(2 CHAR), 
	"COD_JORNADA" VARCHAR2(2 CHAR), 
	"TELEFONO1" VARCHAR2(20 CHAR), 
	"TELEFONO2" VARCHAR2(20 CHAR), 
	"EMAIL" VARCHAR2(100 CHAR), 
	"INDIGENA" VARCHAR2(1 CHAR) DEFAULT 'N', 
	"MODALIDAD_MEP" VARCHAR2(10 BYTE), 
	"CODIGO_MEP" VARCHAR2(10 BYTE),
    CONSTRAINT REG_GENERAL_COLEGIO_PK PRIMARY KEY(CODIGO)
   );
   
   --*****************ESTADO CIVIL****************

CREATE TABLE "REGISTRO"."REG_GENERAL_ESTADO_CIVIL" 
   (	
    "CODIGO" VARCHAR2(1 CHAR), 
	"DESCRIPCION" VARCHAR2(100 CHAR),
    CONSTRAINT REG_GENERAL_ESTCI_PK PRIMARY KEY(CODIGO)
   );

   ---*****************CONVENIO*******************

CREATE TABLE "REGISTRO"."STVATTS" 
   (	
    "STVATTS_CODE" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
	"STVATTS_DESC" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"STVATTS_ACTIVITY_DATE" DATE NOT NULL ENABLE, 
	"STVATTS_SURROGATE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"STVATTS_VERSION" NUMBER(19,0) NOT NULL ENABLE, 
	"STVATTS_USER_ID" VARCHAR2(30 CHAR), 
	"STVATTS_DATA_ORIGIN" VARCHAR2(30 CHAR), 
	"STVATTS_VPDI_CODE" VARCHAR2(6 CHAR),
    CONSTRAINT STVATTS_PK PRIMARY KEY(STVATTS_CODE)
   );
   
--****************************************************************
EXIT