SET DEFINE OFF;

-- Inserts Grupo indigena
insert into DR_SGII_GRUPO_INDIGENA(CODIGO,DESCRIPCION) values('G01','MALEKU');
insert into DR_SGII_GRUPO_INDIGENA(CODIGO,DESCRIPCION) values('G02','BRIBRI');
insert into DR_SGII_GRUPO_INDIGENA(CODIGO,DESCRIPCION) values('G03','CABÉCAR');
insert into DR_SGII_GRUPO_INDIGENA(CODIGO,DESCRIPCION) values('G04','BRUNCA/BORUCA');
insert into DR_SGII_GRUPO_INDIGENA(CODIGO,DESCRIPCION) values('G05','TÉRRABA/TERIBE');
insert into DR_SGII_GRUPO_INDIGENA(CODIGO,DESCRIPCION) values('G06','CHOROTEGA');
insert into DR_SGII_GRUPO_INDIGENA(CODIGO,DESCRIPCION) values('G07','HUETAR');
insert into DR_SGII_GRUPO_INDIGENA(CODIGO,DESCRIPCION) values('G08','NGÄBE');

-- Inserts Territorio indigena
insert into DR_SGII_TERRITORIO_INDIGENA(CODIGO,DESCRIPCION) values('T01','MATAMBÚ');
insert into DR_SGII_TERRITORIO_INDIGENA(CODIGO,DESCRIPCION) values('T02','GUATUSO');
insert into DR_SGII_TERRITORIO_INDIGENA(CODIGO,DESCRIPCION) values('T03','HUETAR DE QUITIRRISÍ');
insert into DR_SGII_TERRITORIO_INDIGENA(CODIGO,DESCRIPCION) values('T04','HUETAR DE ZAPATÓN');
insert into DR_SGII_TERRITORIO_INDIGENA(CODIGO,DESCRIPCION) values('T05','CABÉCAR DE NAIRI-AWARI');
insert into DR_SGII_TERRITORIO_INDIGENA(CODIGO,DESCRIPCION) values('T06','CABÉCAR DE CHIRRIPÓ(Duchii)');
insert into DR_SGII_TERRITORIO_INDIGENA(CODIGO,DESCRIPCION) values('T07','CABÉCAR DE BAJO CHIRRIPÓ');
insert into DR_SGII_TERRITORIO_INDIGENA(CODIGO,DESCRIPCION) values('T08','CABÉCAR DE TAYNI');
insert into DR_SGII_TERRITORIO_INDIGENA(CODIGO,DESCRIPCION) values('T09','BRIBRI DE KEKÖLDI(Cocles)');
insert into DR_SGII_TERRITORIO_INDIGENA(CODIGO,DESCRIPCION) values('T10','CABÉCAR DE TELIRE');
insert into DR_SGII_TERRITORIO_INDIGENA(CODIGO,DESCRIPCION) values('T11','CABÉCAR DE TALAMANCA');
insert into DR_SGII_TERRITORIO_INDIGENA(CODIGO,DESCRIPCION) values('T12','BRIBRI DE TALAMANCA');
insert into DR_SGII_TERRITORIO_INDIGENA(CODIGO,DESCRIPCION) values('T13','BRBRI DE CABAGRA');
insert into DR_SGII_TERRITORIO_INDIGENA(CODIGO,DESCRIPCION) values('T14','BRIBRI DE SALITRE');
insert into DR_SGII_TERRITORIO_INDIGENA(CODIGO,DESCRIPCION) values('T15','CABÉCAR DE UJARRÁS');
insert into DR_SGII_TERRITORIO_INDIGENA(CODIGO,DESCRIPCION) values('T16','CHINA KICHA');
insert into DR_SGII_TERRITORIO_INDIGENA(CODIGO,DESCRIPCION) values('T17','BRUNKA DE BORUCA');
insert into DR_SGII_TERRITORIO_INDIGENA(CODIGO,DESCRIPCION) values('T18','BRUNKA DE CURRÉ(Rey Curré');
insert into DR_SGII_TERRITORIO_INDIGENA(CODIGO,DESCRIPCION) values('T19','GUAYMÍ DE COTO BRUS');
insert into DR_SGII_TERRITORIO_INDIGENA(CODIGO,DESCRIPCION) values('T20','GUAYMÍ DE ABROJOS-MONTEZUMA');
insert into DR_SGII_TERRITORIO_INDIGENA(CODIGO,DESCRIPCION) values('T21','GUAYMÍ DE ALTOS DE SAN ANTONIO');
insert into DR_SGII_TERRITORIO_INDIGENA(CODIGO,DESCRIPCION) values('T22','GUAYMÍ DE CONTEBURICA');
insert into DR_SGII_TERRITORIO_INDIGENA(CODIGO,DESCRIPCION) values('T23','GUAYMÍ DE OSA');
insert into DR_SGII_TERRITORIO_INDIGENA(CODIGO,DESCRIPCION) values('T24','FUERA DE TERRITORIO');

exit

