drop table REGISTRO.DR_SGII_NO_CALIFICA;
drop table REGISTRO.DR_SGII_RESPONSABLES_PROMOCION;
drop table REGISTRO.DR_SGII_SOLICITUD;
drop table REGISTRO.DR_SGII_PROMOCION;
drop table REGISTRO.DR_SGII_PERSONA;
drop table REGISTRO.DR_SGII_BITACORA_FUNCIONARIO;
drop table REGISTRO.DR_SGII_BITACORA_POSTULANTE;
drop table REGISTRO.DR_SGII_TERRITORIO_INDIGENA;
drop table REGISTRO.DR_SGII_GRUPO_INDIGENA;


--*************GRUPO INDIGENA****************************

CREATE TABLE REGISTRO."DR_SGII_GRUPO_INDIGENA"
(
    "CODIGO" VARCHAR2(4) NOT NULL ENABLE,
    "DESCRIPCION" VARCHAR2(35),
    CONSTRAINT "DR_SGII_GRUPO_INDIGENA_PK" PRIMARY KEY(CODIGO)
);

--*************TERRITORIO INDIGENA****************************

CREATE TABLE REGISTRO."DR_SGII_TERRITORIO_INDIGENA"
(
    "CODIGO" VARCHAR2(4) NOT NULL ENABLE,
    "DESCRIPCION" VARCHAR2(50),
    CONSTRAINT "DR_SGII_TERRITORIO_INDIGENA_PK" PRIMARY KEY(CODIGO)
);

--*************BITACORA POSTULANTE****************************

CREATE TABLE REGISTRO."DR_SGII_BITACORA_POSTULANTE"
(
    "FECHA_HORA_INGRESO" TIMESTAMP(2) NOT NULL ENABLE,
    "USUARIO" VARCHAR2(10) NOT NULL ENABLE,
    "MOVIMIENTO" VARCHAR2(50) NOT NULL ENABLE,
    "FECHA_HORA_MOVIMIENTO" TIMESTAMP(2) NOT NULL ENABLE
);

--*************BITACORA FUNCIONARIO****************************
CREATE TABLE REGISTRO."DR_SGII_BITACORA_FUNCIONARIO"
(
    "FECHA_HORA_INGRESO" TIMESTAMP(2) NOT NULL ENABLE,
    "USUARIO" VARCHAR2(10) NOT NULL ENABLE,
    "MOVIMIENTO" VARCHAR2(50) NOT NULL ENABLE,
    "FECHA_HORA_MOVIMIENTO" TIMESTAMP(2) NOT NULL ENABLE,
    "MOTIVO" VARCHAR2(60) NOT NULL ENABLE
);

--*************PERSONA****************************

CREATE TABLE REGISTRO."DR_SGII_PERSONA"
(
    "IDENTIFICACION" VARCHAR2(20) NOT NULL ENABLE,
    "CODIGO_TIPO_IDENTIFICACION" VARCHAR2(10) NOT NULL ENABLE,
    "NOMBRE" VARCHAR2(30) NOT NULL ENABLE,
    "PRIMER_APELLIDO" VARCHAR2(25) NOT NULL ENABLE,
    "SEGUNDO_APELLIDO" VARCHAR2(25),
    "CONOCIDO_COMO" VARCHAR2(50),
    "FECHA_NACIMIENTO" DATE NOT NULL ENABLE,
    "CODIGO_COLEGIO" VARCHAR2(10),
    "ANIO_GRADUACION_COLEGIO" INT,
    "NOTA_COLEGIO" NUMBER,
    "INDIGENA" CHAR,
    "CODIGO_TERRITORIO" VARCHAR2(10),
    "CODIGO_GRUPO_INDIGENA" VARCHAR2(10),
	"CORREO_ELECTRONICO" VARCHAR2(50) NOT NULL ENABLE,
	"TELEFONO" INT NOT NULL ENABLE,
	"ESTADO_EN_SISTEMA" VARCHAR2(1) NOT NULL ENABLE, 
    CONSTRAINT "DR_SGII_PERSONA_PK" PRIMARY KEY(IDENTIFICACION),
    CONSTRAINT "DR_SGII_PERSONA_FK1" FOREIGN KEY(CODIGO_TIPO_IDENTIFICACION) REFERENCES "REG_ADMIS_TIPO_IDENTIFICACION"(CODIGO),
    CONSTRAINT "DR_SGII_PERSONA_FK2" FOREIGN KEY(CODIGO_COLEGIO) REFERENCES "REG_GENERAL_COLEGIO"(CODIGO),
    CONSTRAINT "DR_SGII_PERSONA_FK3" FOREIGN KEY(CODIGO_GRUPO_INDIGENA) REFERENCES REGISTRO."DR_SGII_GRUPO_INDIGENA"(CODIGO),
    CONSTRAINT "DR_SGII_PERSONA_FK4" FOREIGN KEY(CODIGO_TERRITORIO) REFERENCES REGISTRO."DR_SGII_TERRITORIO_INDIGENA"(CODIGO)
);

--*************PROMOCION****************************
CREATE TABLE REGISTRO."DR_SGII_PROMOCION" 
(
    "CODIGO_PROMOCION" VARCHAR2(50) NOT NULL ENABLE,
	"NUMERO_PROMOCION" INT NOT NULL ENABLE,
	"DESCRIPCION_PROMOCION" VARCHAR(500) NOT NULL ENABLE,
    "CODIGO_GRUPO_DE_INTERES" VARCHAR2(4) NOT NULL ENABLE,
    "CODIGO_CARRERA" VARCHAR2(12) NOT NULL ENABLE,
    "CODIGO_PERIODO" VARCHAR2(10) NOT NULL ENABLE,
    "CODIGO_UNIDAD_ACADEMICA" VARCHAR2(15) NOT NULL ENABLE,
    "CUPOS" INT,
    "FECHA_INICIO_PROMOCION" DATE NOT NULL ENABLE,
    "FECHA_FIN_PROMOCION" DATE NOT NULL ENABLE,
    "ESTADO_PROMOCION" VARCHAR2(30) NOT NULL ENABLE
);

--*************SOLICITUD****************************

CREATE TABLE REGISTRO."DR_SGII_SOLICITUD"
(
    "IDENTIFICACION_SOLICITUD" VARCHAR2(50) NOT NULL ENABLE,
    "IDENTIFICACION_PERSONA" VARCHAR2(20) NOT NULL ENABLE,
    "GENERO" VARCHAR2(10) NOT NULL ENABLE,
    "ESTADO_SOLICITUD_1" INT NOT NULL ENABLE,
    "ESTADO_SOLICITUD_2" INT,
    "CODIGO_UBICACION" VARCHAR2(10) NOT NULL ENABLE,
    "DIRECCION_EXACTA" VARCHAR2(50) NOT NULL ENABLE,
    "CODIGO_ESTADO_CIVIL" VARCHAR2(1) NOT NULL ENABLE,
    "ADECUACION" CHAR,
    "CODIGO_NACIONALIDAD" VARCHAR2(5) NOT NULL ENABLE,
    "OBSERVACIONES" VARCHAR2(500),
	"NUMERO_PROMOCION" INT NOT NULL ENABLE,
    "CODIGO_PROMOCION_1" VARCHAR2(50) NOT NULL ENABLE,
    "CODIGO_PROMOCION_2" VARCHAR2(50),
    CONSTRAINT "DR_SGII_SOLICITUD_PK" PRIMARY KEY(IDENTIFICACION_SOLICITUD),
    CONSTRAINT "DR_SGII_SOLICITUD_FK1" FOREIGN KEY(CODIGO_ESTADO_CIVIL) REFERENCES "REG_GENERAL_ESTADO_CIVIL"(CODIGO),
    CONSTRAINT "DR_SGII_SOLICITUD_FK2" FOREIGN KEY(IDENTIFICACION_PERSONA) REFERENCES REGISTRO."DR_SGII_PERSONA"(IDENTIFICACION)
);

--*************RESPONSABLES PROMOCION****************************

CREATE SEQUENCE REGISTRO.DR_SGII_SEC_RESP_PROM;

CREATE TABLE REGISTRO."DR_SGII_RESPONSABLES_PROMOCION"
(	"INDEX_RESPONSABLES_PROMOCION" INT NOT NULL,
    "NUMERO_PROMOCION" INT NOT NULL ENABLE,
    "CORREO" VARCHAR2(30) NOT NULL ENABLE,
    "DESCRIPCION" VARCHAR2(50),
	CONSTRAINT "DR_SGII_RESPONSABLES_PRO_PK" PRIMARY KEY(INDEX_RESPONSABLES_PROMOCION)
);

--*************NO CALIFICA****************************

CREATE TABLE REGISTRO."DR_SGII_NO_CALIFICA"
(
    "IDENTIFICACION" VARCHAR2(20) NOT NULL ENABLE,
    "MOTIVO" VARCHAR2(50),
    CONSTRAINT "DR_SGII_NO_CALIFICA_PK" PRIMARY KEY(IDENTIFICACION),
    CONSTRAINT "DR_SGII_NOCALIFICA_FK1" FOREIGN KEY(IDENTIFICACION) REFERENCES REGISTRO."DR_SGII_PERSONA"(IDENTIFICACION)
);

--****************************************************************

CREATE OR REPLACE PUBLIC SYNONYM "DR_SGII_GRUPO_INDIGENA" FOR REGISTRO."DR_SGII_GRUPO_INDIGENA";
CREATE OR REPLACE PUBLIC SYNONYM "DR_SGII_TERRITORIO_INDIGENA" FOR REGISTRO."DR_SGII_TERRITORIO_INDIGENA";

EXIT